const perform = (z, bundle) => {
  const options = {
    url: 'https://api.datacite.org/providers',
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Accept: 'application/json',
    },
    body: {
      data: {
        attributes: {
          symbol: bundle.inputData.symbol,
          name: bundle.inputData.name,
          displayName: bundle.inputData.displayName,
          memberType: bundle.inputData.memberType,
          systemEmail: bundle.inputData.systemEmail,
          passwordInput: bundle.inputData.passwordInput,
          confirmPasswordInput: bundle.inputData.confirmPasswordInput,
          description: bundle.inputData.description,
          organisationType: bundle.inputData.organisationType,
          region: bundle.inputData.region,
          website: bundle.inputData.website,
          focusArea: bundle.inputData.focusArea,
          groupEmail: bundle.inputData.groupEmail,
          billingStreet: bundle.inputData.billingStreet,
          billingPostalCode: bundle.inputData.billingPostalCode,
          billingCity: bundle.inputData.billingCity,
          billingDepartment: bundle.inputData.billingDepartment,
          billingOrganization: bundle.inputData.billingOrganization,
          billingCountryCode: bundle.inputData.billingCountryCode,
          twitter: bundle.inputData.twitter,
          rorId: bundle.inputData.rorId,
        },
        type: 'providers',
      },
    },
  };

  return z.request(options).then((response) => {
    response.throwForStatus();
    const results = response.json;

    // You can do any parsing you need for results here before returning them

    return results;
  });
};

module.exports = {
  operation: {
    perform,
    inputFields: [
      {
        key: 'symbol',
        label: 'Account ID',
        type: 'string',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'name',
        label: 'Name',
        type: 'string',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'displayName',
        label: 'Display Name',
        type: 'string',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'memberType',
        label: 'Member Type',
        choices: ['consortium_organization', 'consortium', 'direct_member', 'member_only', 'contractual_member', 'registration_agency'],
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'systemEmail',
        label: 'System Email',
        type: 'string',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'passwordInput',
        label: 'Password',
        type: 'password',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'confirmPasswordInput',
        label: 'Confirm Password',
        type: 'password',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'description',
        label: 'Description',
        type: 'text',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'organisationType',
        label: 'Sector',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'region',
        label: 'Region',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'website',
        label: 'Website',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'groupEmail',
        label: 'Group Email',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'billingStreet',
        label: 'Billing Street',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'billingPostalCode',
        label: 'Billing PostalCode',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'billingCity',
        label: 'Billing City',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'billingDepartment',
        label: 'Billing Department',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'billingOrganization',
        label: 'Billing Organization',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'billingCountryCode',
        label: 'Billing CountryCode',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'twitter',
        label: 'twitter',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'rorId',
        label: 'ROR ID',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
    ],
  },
  key: 'create_production_account',
  noun: 'Account',
  display: {
    label: 'Create Production Member Account',
    description: 'Create a Production Account in Fabrica for a Member',
    hidden: false,
    important: true,
  },
};
